version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "3000:7000"
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: LFwfC6fx3HYmrJDWVgNZauRsfaexY5FmBri5QyPwK3C2XvXERFE2YyMdAj352wxpR3v
        port: 7000
        databases:
          default:
            connector: localhost
            host: localhost
            port: 3306
            user: root
            password: prisma
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: ~
